### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by pbayer** [pbayer/DiscreteEvents.jl#13]
As @John_Gibson [pointed out](https://discourse.julialang.org/t/simulate-v0-2-0-a-julia-package-for-discrete-event-simulation/31822) it would be appropriate to rename the package. I like his suggestion to name it `DiscreteEvent.jl`.

**Comment by non-Jedi** [comment]
I think that the word "simulate" is more important to the package's identity than "discrete" since "discrete" is already implied by "event". Personally, I would go for something like "EventSim".

**Comment by pbayer** [comment]
In the long term we need a domain-specific ecosystem in Julia for simulation like `BioJulia`, `JuliaOpt`, `EcoJulia`, `JuliaStats`. Currently we have three packages for discrete event simulation 😒, each with `Sim` in the name. At the moment it makes sense to keep them separate from an evolutionary perspective.

There is no `JuliaSim` yet and `SimJulia.jl` is another package. This commends for the time being to keep the `Sim` in the package name as you suggest.

**Comment by pbayer** [comment]
`EventSim.jl` is a name perhaps too close to [`EventSimulation.jl`](https://github.com/bkamins/EventSimulation.jl), one of the other two packages. `SimEvent.jl`would be another option but sounds a bit like MathWorks [`SimEvents`](https://en.wikipedia.org/wiki/SimEvents). 😕

**Comment by vancleve** [comment]
seems like `SimulateEvents.jl` is a natural option :-)

**Comment by non-Jedi** [comment]
I also like DiscreteSim.jl as a clear and unencumbered option.

**Comment by pbayer** [comment]
Here's a word play:
- `DESim.jl` is short and uses the acronym DES for discrete event systems,
- `EvtSim.jl`: this I don't like so much, 
- `DevSim.jl` is my favourite, I like also the *dev*elopment idea in it, sounds like something practical, useful (interferes with [DEVS](https://en.wikipedia.org/wiki/DEVS), though not too much due to camel case), 
- `DiscreteEvSim.jl` is not so bad either, albeit not so short,
…

**Comment by swissr** [comment]
I'm just reading up. -- I like `DESim.jl` because it fits well into the wikipedia articles (sorry german) [DES](https://de.wikipedia.org/wiki/Ereignisorientierte_Simulation) and [Discrete Simulation](https://de.wikipedia.org/wiki/Diskrete_Simulation). I also like the first proposition `DiscreteEvent.jl`; within a Simulation ecosystem domain it specifies what the package is about.

From the first wikipedia link I'm not sure about `DiscreteSim.jl`, it seemed to me that this term is more generic than discrete event simulation.

**Comment by pbayer** [comment]
`DESimulate.jl` would maintain the connection with the current package name. I still also like `DiscreteEvent.jl`, but can we bet that a Julia simulation ecosystem will emerge? It should!

**Comment by non-Jedi** [comment]
This is becoming a pretty bad "bikeshed", so this will probably be my last response.

I'd strongly recommend avoiding abbreviations and acronyms that are not well-known to the general population ("Sim" is well-known to be shorthand for "Simulation", but "Ev" isn't for "Event" nor "DES" for "Discrete Event Simulation" outside of a tiny segment of the population). In fact there [used to be a section in the manual](https://discourse.julialang.org/t/package-naming-guidelines-missing-from-manual/32920) outlining this suggestion ([see it on the wayback machine here](https://web.archive.org/web/20180724155513/https://docs.julialang.org/en/stable/manual/packages/#Guidelines-for-naming-a-package-1)). I'm not super invested in which specific package name is picked, but I would strongly prefer it not have an inscrutable abbreviation in it.

Of the suggestions shared so far, I've come to like `DiscreteEvent` (I think `DiscreteEvents` is slightly less awkward, but that's a whole 'nother bikeshed) or `SimulateEvents` best the more I think about it. They are relatively long, but they're clear on the package's purpose, and you only have to type `using SimulateEvents` once.

**Comment by pbayer** [comment]
Thank you for pointing out the guidelines regarding abbreviations and also for the funny suggestions 😆. Yes, `DiscreteEvents.jl` and `SimulateEvents.jl` are both fine.

**Comment by pbayer** [comment]
`Simulate.jl` has been renamed to `DiscreteEvents.jl` and successfully built on CI. GitHub maintains the old links and redirects them to the renamed package.

**Comment by ga72kud** [comment]
@pbayer what is the actual package  simulate or discreteEvents? What will be supported?
