### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by pbayer** [pbayer/DiscreteEvents.jl#16]
Develop multithreading 
- [x] register events, samples, processes
- [x] run the (parallel) clock
- [x] interface for controlling active clocks
- [x] integrate with master clock
- [x] spawn processes
- [x] group simulations

this will be done after release 0.3
- sync clocks
- load balancing

**Comment by pbayer** [comment]
## The idea is as follows:
1. Develop an event handler (based on the current one) executing all events in the given event queue up to a given time,
2. Then event queues and event handlers can be parallelised onto several threads (if the user wants to),
3. The clock synchronises the event handlers at each Δt time step via a sync channel.

The event handler is an active object running through to completion. So there is no synchronisation between parallel events during the Δt time intervals (unless an event requires explicit synchronisation).

This introduces an amount of **Δt uncertainty** regarding the execution order of parallel events. The user can reduce the uncertainty by a) setting Δt to a smaller value or b) requesting explicit synchronisation but thus synchronisation has to occur more often and parallelism is reduced.

**Comment by zhangliye** [comment]
A lot of new features and lots of new code in v0.3.  Look forward to the new release. 
Is this the  most difficult part for the release of v0.3? The author of SimJulia has some comments of parallel computing on  simulation with multiple cores. 

> Running a complex simulation in a parallel way is not possible in SimJulia. All events are executed synchronously. We have simulated fairly complex scenarios without any problems. How many processes are running simultaneously?
I have seen your question in Julia Discourse and the answers. I don't agree but I have not the intention to start a discussion. Resumable functions transforms a process in a state machine and entering a state machine is simply a function call based on a triggered event. Whatever event framework you will be using it will not be faster than SimJulia, ... and you get some nice spaghetti code of interacting events.
Even of you don't intent to continue working with SimJulia, can you keep me informed about your progress.
Kind regards.

[Parallel calculation using multiple cores](https://github.com/BenLauwens/SimJulia.jl/issues/64)

**Comment by pbayer** [comment]
He is right under some assumptions:

1. **Global time**: each reference to the clock has to be synchronized over the threads. This is expensive.
2. **Responsiveness**: as long as simulations run only seconds or fractions of a second, parallelising doesn't make much sense from a user perspective.
3. **Optimization potential**: often you can speed up drastically by changing the model or doing some other tricks. See for example [this issue](https://github.com/pbayer/DiscreteEventsCompanion.jl/issues/1) on `DiscreteEventsCompanion`.

But those assumptions are not always satisfied. In this context I remember also [Linus Thorvalds′ remark on parallel computing](http://highscalability.com/blog/2014/12/31/linus-the-whole-parallel-computing-is-the-future-is-a-bunch.html).

I am more concerned about how to make it work. Recently I came over a quote from over 30 years ago outlining the problem:

> The concept of a unique global clock is not meaningful 'in the context of a distributed system of self-contained 
> parallel agents. ...
> 
> We may conclude that, for a distributed system, a unique (linear) global time is not definable. ...
> 
> This is not to imply that it is impossible to construct a distributed system whose behavior is such that the elements 
> of the system can be abstractly construed as acting synchronously. ... Assume one element, called the *global master*, 
> controls when each of the elements in the system may continue; ...
> 
> The important point to be made is that any such global synchronization creates a bottleneck which can be extremely 
> inefficient in the context of a distributed environment.

Now it gets more interesting:

> Although systems designed to act synchronously may be useful in some particular applications, we will deal with the 
> general asynchronous distributed environment; the behavior of the synchronous system can always
> be derived as a special case. 
> 
> Gul Agha: Actors, A Model of Concurrent Computation in Distributed Systems.- 1986, MIT Press, 9ff)

Thus if we **drop the assumption of global synchronous time**, we can parallelize and synchronize from time to time but not for every event in the system. 

Let me give you an example: If we want to do a simulation of an automotive plant consisting of a body shop, a paint shop and several coupled assembly lines, we don't need to synchronize every operation in the body shop with every other operation in the finish assembly line. It is sufficient to synchronize the sections every virtual minute and we will still be able to get meaningful simulation results for the plant.

This shows what has to be done to parallelize simulations:
- we need a synchronization mechanism and 
- we must (be able to) compose and distribute our simulation events or entities in a meaningful way.

Therefore - since this is not easy - multithreading in `DiscreteEvents` will be and remain **experimental** for some time and as I hope, you will help to gain some experience with it in order to improve it.

**Comment by pbayer** [comment]
- Examples are up and running.
- Documentation is complete
- Multithreading is marked **experimental** in documentation.
