### ISSUE TITLE
Error in the document

### ISSUE THREAD

**Issue by zhangliye** [pbayer/DiscreteEvents.jl#20]
On the following page of the document for v0.2, [examples/singleserver](https://pbayer.github.io/DiscreteEvents.jl/v0.2.0/examples/singleserver/) 

` 
sample_time!(𝐶, 0.1)  # we determine the sample rate 

Sim.sample!(𝐶, SF(stats));  # we register stats() as sampling function
`

Should be 
`
sample_time!(𝐶, 0.1)  # we determine the sample rate

Simulate.sample!(𝐶, SF(stats));  # we register stats() as sampling function
`

## To do
- [x] include example files into testing

**Comment by pbayer** [comment]
Hello,
thank you for pointing out such errors. This was due to a former name change. 

I have to ensure in future releases that all examples run properly by including them in the testing.

**Comment by zhangliye** [comment]
I like this package very much, especially the parallel calculation part. I have experience of using simulation packages in Julia, such as SimJulia.jl.  I would like to contribute to this project. Thanks for your great work.

**Comment by pbayer** [comment]
The parallel part is not yet user ready. I hope to change that in the next few weeks.

You are very welcome to contribute. There are various ways to contribute, e.g.
- pointing out errors and inconsistencies,
- doing examples, tests and benchmarks,
- helping in documentation,
- contributing code, PR's …

 I will setup a **current** project board in order to make the topics I'm working upon more visible. Then perhaps it is easier to contribute.

**Comment by zhangliye** [comment]
Great!

**Comment by pbayer** [comment]
I have updated the issues to reflect the issues I'm working on. 

All this is synced to a [Glo board](https://www.gitkraken.com/glo). If you want to use GitKraken Glo, please drop me an email and I can invite you to the board. Otherwise simply contribute to the issues.

Thank you in advance.

**Comment by pbayer** [comment]
I have enhanced testing such that `*.jl` and `*.ipynb` files in `examples/src` and `examples/nb` get executed as a last test step. Thus they are integrated in CI.

**Comment by zhangliye** [comment]
@pbayer  I am not familiar with that kind of tools. I think I work on some simple things first and then contribute more.  I do not want to mess the current code.

**Comment by pbayer** [comment]
now examples and notebooks are evaluated within their own module,
so no more namespace collisions during testing.

all examples are working and included in testing.
