### ISSUE TITLE
Real time clock

### ISSUE THREAD

**Issue by pbayer** [pbayer/DiscreteEvents.jl#22]
- [x] implementation
- [x] testing
- [x] examples
- [x] documentation

**Comment by itsdfish** [comment]
Hello @pbayer . I have been interested in trying v0.3.0. When is your next release scheduled?

**Comment by pbayer** [comment]
Hello, thank you for the interest. Currently I'm occupied with other things. I can resume working on DiscreteEvents again in about two weeks. So I hope, you have the patience to wait until June 2020.

**Comment by itsdfish** [comment]
Yes of course. I appreciate your hard work and look forward to the new release.

**Comment by zhangliye** [comment]
Glad to hear that! I have checked the code and found a lot of new features. Very exited to see that!

**Comment by pbayer** [comment]
Hi,

After other projects only now I come back to `DiscreteEvents` and will try to get the new stuff working in the days and weeks coming. Sorry  for the delays. Hopefully what I learned in the meantime will be helpful.

**Comment by itsdfish** [comment]
No problem. Thanks for the update. I look forward to the new release!

**Comment by pbayer** [comment]
Now this is documented with commit 7c4c0feb60ef5ed9b64e6d0c25c62eda8d1b6418
and ready for release. I declared this experimental. But so far all works well.
I close this now.
