### ISSUE TITLE
Simplify and streamline documentation

### ISSUE THREAD

**Issue by pbayer** [pbayer/DiscreteEvents.jl#23]
- [x] transfer complementary docs to Companion
- [x] simplify usage.md
- [x] provide/rewrite introductory examples

**Comment by zhangliye** [comment]
The examples of SimPy is organized in the categories of features.  I find it is easy for the new users to write hie/her own simulation quickly according to the corresponding example.  Some of the examples of  are organized as the categories,

**Condition events**
- Bank Renege
- Movie Renege 

**Interrupts**
- Machine Shop

**Resources: Container**
- Gas Station Refueling

**Comment by pbayer** [comment]
Now I rewrote the [introductory examples](https://pbayer.github.io/DiscreteEvents.jl/dev/intro/) giving one example each for
1. event based and
2. process based simulation.

Those are serious examples and no toy examples anymore. 
[More examples](https://pbayer.github.io/DiscreteEventsCompanion.jl/dev/examples/examples/) are on `DiscreteEventsCompanion`.
