### ISSUE TITLE
Suggest updating README.md

### ISSUE THREAD

**Issue by magister-ludi** [pbayer/DiscreteEvents.jl#24]
This isn't very serious, but I thought it worth pointing out. Although the repo is called `DiscreteEvents` the package is called `Simulate`. The `README.md` file hasn't been updated to reflect this, either in the description for installation or in the sample code.

**Comment by pbayer** [comment]
Thank you, I included a note referring the package renaming from `Simulate.jl`.

**Comment by magister-ludi** [comment]
Part of my point was that the instructions and the code provided in `README.md` won't work in their present form. The change you made is good, and in a good position, but I think that the remainder of the document should refer to `Simulate` instead of `DiscreteEvents`.

Should I perhaps rewrite the way I think would be useful, and then do a PR?

**Comment by pbayer** [comment]
Working instructions and code for the registered package are in [Simulate.jl](https://github.com/pbayer/DiscreteEvents.jl/tree/v0.2.0). I include this link in the current `README.md` and hope this solves the confusion for now. If there is a better way, your PR is welcome. 

The gap between repo and registered package is resolved when the new v0.3 is released in some weeks.

**Comment by magister-ludi** [comment]
You clearly have ongoing plans, so I won't attempt to interfere at this point. I'll leave the issuev open, and close it (or submit a PR) after your update.

**Comment by pbayer** [comment]
sorry, now I have seen what you meant. I updated the introductory example.

**Comment by magister-ludi** [comment]
The updated package looks great. I look forward to trying it out.
