### ISSUE TITLE
Documentation request: vs SimJulia

### ISSUE THREAD

**Issue by hdavid16** [pbayer/DiscreteEvents.jl#28]
It would be great if the documentation had a section describing the differences with SimJulia.jl.

**Comment by pbayer** [comment]
Hi, maybe my [announcement on Discourse](https://discourse.julialang.org/t/ann-discreteevents-0-3/46477) answers those questions. Pretty everything announced there is - as far as I know - not a feature in other Julia discrete event simulation packages.

**Comment by hdavid16** [comment]
Sounds good. I just thought a brief description of these differences with SimJulia in the docs could be helpful for those who are considering which DES package to use. Looking forward to the ongoing development of your package.
