### ISSUE TITLE
Feature request: macros

### ISSUE THREAD

**Issue by hdavid16** [pbayer/DiscreteEvents.jl#29]
Have you considered defining macros for main commands (i.e. @run)?
- [x] Complete macros
- [x] Include into documentation
- [x] Include into testing
- [x] update examples
- [x] release 0.3.1
- [x] announce on discourse

**Comment by pbayer** [comment]
yes, I did consider macros and I think they could be a great addition, mainly `@fun`, `@Prc`, `@process!`, `@event!` and friends. I would like if somebody joined me with some help.

**Comment by hdavid16** [comment]
Sounds good. I'll see if I can make some time in the next couple of weeks to take a look at that implementation.￼￼

**Comment by hdavid16** [comment]
@process, @event, @run! added: https://github.com/pbayer/DiscreteEvents.jl/pull/30#issue-485896653

**Comment by pbayer** [comment]
@hdavid16 thank you very much for your PR! This is a great addition.

Could you please complete the macros as suggested in the PR?
Then I merge, do the integration into documentation and testing
and release 0.3.1.

**Comment by pbayer** [comment]
I reopen now for steps 2..4

**Comment by pbayer** [comment]
With the above commits I

- updated the 2-argument @event macro to accept a 1) function call, 2) an anonymous function and 3) a time argument,
- added a @periodic macro,
- updated docs and examples

**Comment by pbayer** [comment]
## Release DiscreteEvents 0.3.1

Introduces a macro API with contributions of @hdavid16 

@JuliaRegistrator register

**Comment by pbayer** [comment]
everything done. Hopefully this time more interest and feedback on discourse!

Thank you very much @hdavid16 .
