### ISSUE TITLE
Update Distributions to v0.24

### ISSUE THREAD

**Issue by itsdfish** [pbayer/DiscreteEvents.jl#32]
Hello-

I was wondering whether you would be willing to update your Project.toml to allow Distributions v0.24.0? Right now that is creating a conflict with my other dependencies. Using CompatHelper would automate this task for you.

Thank you!

**Comment by pbayer** [comment]
## Register `DiscreteEvents` v0.3.2

@JuliaRegistrator register

Release notes:

- compatibility with `Distributions` 0.24
- GitHub CI workflow

**Comment by pbayer** [comment]
Thank you, `DiscreteEvents` ─ v0.3.2 with updated compat entries is available from the Julia registry.

**Comment by itsdfish** [comment]
Thanks for updating Distributions. By the way, I have found [CompatHelper](https://github.com/JuliaRegistries/CompatHelper.jl) to be convenient for automating dependency upgrades. All you have to do is add a file to your workflow.
