### ISSUE TITLE
Distributions 0.25 compatibility

### ISSUE THREAD

**Issue by filchristou** [pbayer/DiscreteEvents.jl#45]
I have local conflicts because DiscreteEvents.jl doesn't support Distributions 0.25
I saw a bunch of PRs from the CompatHelper for that but the checks fail.
However I tried it locally and all the tests pass.
Do we know what is the problem and there is such trouble with Distributions 0.25 ?

**Comment by hdavid16** [comment]
The `[compat]` section in the `Project.toml` needs to be updated to allow 0.25. @pbayer, can you merge the compat helper pull request for this?

**Comment by pbayer** [comment]
`DiscreteEvents` v0.3.5 is available from the Julia registry.
